In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
file_rotterdamPortData = r'..\data\rotterdam_dataset_16.xlsx'
wd = pd.read_excel(file_rotterdamPortData)
wd.info()
wd.head()

<class 'pandas.DataFrame'>
RangeIndex: 11076 entries, 0 to 11075
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Arrival_Date   11076 non-null  datetime64[us]
 1   Vessel_ID      11076 non-null  str
 2   Vessel_Type    11076 non-null  str
 3   Cargo_tons     11076 non-null  int64
 4   Berth_Time_hr  11076 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 432.8 KB

         Arrival_Date Vessel_ID Vessel_Type  Cargo_tons  Berth_Time_hr
0 2022-01-01 23:51:00   V000001   Container       18379           17.2
1 2022-01-01 15:07:00   V000002   Container       22886           20.2
2 2022-01-01 08:29:00   V000003   Container       13054           19.3
3 2022-01-01 21:33:00   V000004      Tanker       40882           35.7
4 2022-01-01 09:07:00   V000005        Bulk       45645           27.2

In [28]:
wd.loc[2]
wd.describe()
wd.sort_values(by='Vessel_ID')
wd.sort_values(by='Vessel_Type')
wd.sort_values(by='Arrival_Date')

             Arrival_Date Vessel_ID Vessel_Type  Cargo_tons  Berth_Time_hr
2     2022-01-01 08:29:00   V000003   Container       13054           19.3
4     2022-01-01 09:07:00   V000005        Bulk       45645           27.2
1     2022-01-01 15:07:00   V000002   Container       22886           20.2
3     2022-01-01 21:33:00   V000004      Tanker       40882           35.7
0     2022-01-01 23:51:00   V000001   Container       18379           17.2
...                   ...       ...         ...         ...            ...
11067 2024-12-30 19:40:00   V011068   Container        8070           16.2
11073 2024-12-31 02:32:00   V011074   Container       13826           18.7
11075 2024-12-31 03:39:00   V011076        Bulk       60693           29.2
11074 2024-12-31 19:39:00   V011075        Bulk       21663           27.2
11072 2024-12-31 21:52:00   V011073   Container       11137           14.7

[11076 rows x 5 columns]

In [ ]:
# investigate if there are duplicates
print(wd.duplicated().sum()) # no duplicated entries 
print(wd.duplicated(subset=["Vessel_ID"]).sum())
print(wd.isnull().sum().sum()) # no missing data 
print(wd.isnull().sum()[wd.isnull().sum() > 0])
print(wd.dtypes)
print(wd.describe)

print((wd['Berth_Time_hr'] < 0).sum())
print((wd['Cargo_tons'] < 0).sum())

Arrival_Date     datetime64[us]
Vessel_ID                   str
Vessel_Type                 str
Cargo_tons                int64
Berth_Time_hr           float64
dtype: object
0
0

In [ ]:
#investigate more with plotting the data