In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
file_rotterdamPortData = r'..\data\rotterdam_dataset_16.xlsx'
wd = pd.read_excel(file_rotterdamPortData)
wd.info()
wd.head()

<class 'pandas.DataFrame'>
RangeIndex: 11076 entries, 0 to 11075
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Arrival_Date   11076 non-null  datetime64[us]
 1   Vessel_ID      11076 non-null  str
 2   Vessel_Type    11076 non-null  str
 3   Cargo_tons     11076 non-null  int64
 4   Berth_Time_hr  11076 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 432.8 KB

         Arrival_Date Vessel_ID Vessel_Type  Cargo_tons  Berth_Time_hr
0 2022-01-01 23:51:00   V000001   Container       18379           17.2
1 2022-01-01 15:07:00   V000002   Container       22886           20.2
2 2022-01-01 08:29:00   V000003   Container       13054           19.3
3 2022-01-01 21:33:00   V000004      Tanker       40882           35.7
4 2022-01-01 09:07:00   V000005        Bulk       45645           27.2

In [13]:
# check if Categories of Vessels are balanced
counts = wd['Vessel_Type'].value_counts()
shares = (counts / counts.sum() * 100).round(2)

composition = pd.DataFrame({'Count': counts, 'Share(%)': shares})
composition.loc['Total'] = [composition['Count'].sum(), composition['Share(%)'].sum()]
print(composition)
# From the result, we can forsee that N(t) decomposition will be container-dominated

               Count  Share(%)
Vessel_Type
Container     6117.0     55.23
Bulk          2515.0     22.71
Tanker        2444.0     22.07
Total        11076.0    100.01

In [7]:
wd.loc[2]
wd.describe()
print(wd[['Cargo_tons', 'Berth_Time_hr']].describe())
print("Date range:", wd['Arrival_Date'].min(), "->", wd['Arrival_Date'].max())
print("Span:", wd['Arrival_Date'].max() - wd['Arrival_Date'].min())

          Cargo_tons  Berth_Time_hr
count   11076.000000   11076.000000
mean    30222.808776      25.292678
std     20788.652031       7.126805
min      3991.000000       8.800000
25%     14285.750000      19.700000
50%     21522.000000      23.400000
75%     43692.250000      30.700000
max    151271.000000      45.800000
Date range: 2022-01-01 08:29:00 -> 2024-12-31 21:52:00
Span: 1095 days 13:23:00

In [ ]:
#Descriptive Statistics
wd[['Cargo_tons', 'Berth_Time_hr']].agg(['mean', 'median','std', 'skew', 'kurt'])

          Cargo_tons  Berth_Time_hr
mean    30222.808776      25.292678
median  21522.000000      23.400000
std     20788.652031       7.126805
skew        1.208645       0.528089
kurt        1.154122      -0.765433

In [ ]:
# investigate if there are duplicates
print(wd.duplicated().sum()) # no duplicated entries 
print(wd.duplicated(subset=["Vessel_ID"]).sum())


# investigate if there are missing values
print(wd.isnull().sum().sum()) # no missing data 
print(wd.isnull().sum()[wd.isnull().sum() > 0])
print(wd.dtypes)
print(wd.describe)

# Consitency check 
print((wd['Berth_Time_hr'] < 0).sum())
print((wd['Cargo_tons'] < 0).sum())

# check if each vessel ID has one unit corresponding vessel type
wd.groupby('Vessel_ID')['Vessel_Type'].nunique().value_counts()

0
0
0
Series([], dtype: int64)
Arrival_Date     datetime64[us]
Vessel_ID                   str
Vessel_Type                 str
Cargo_tons                int64
Berth_Time_hr           float64
dtype: object
<bound method NDFrame.describe of              Arrival_Date Vessel_ID Vessel_Type  Cargo_tons  Berth_Time_hr
0     2022-01-01 23:51:00   V000001   Container       18379           17.2
1     2022-01-01 15:07:00   V000002   Container       22886           20.2
2     2022-01-01 08:29:00   V000003   Container       13054           19.3
3     2022-01-01 21:33:00   V000004      Tanker       40882           35.7
4     2022-01-01 09:07:00   V000005        Bulk       45645           27.2
...                   ...       ...         ...         ...            ...
11071 2024-12-30 05:15:00   V011072        Bulk       63631           33.4
11072 2024-12-31 21:52:00   V011073   Container       11137           14.7
11073 2024-12-31 02:32:00   V011074   Container       13826           18.7
11074 2024-12-31 19:39:00   V011075        Bulk       21663           27.2
11075 2024-12-31 03:39:00   V011076        Bulk       60693           29.2

[11076 rows x 5 columns]>
0
0

Vessel_Type
1    11076
Name: count, dtype: int64

In [ ]:
# 4.1 investigate more with plotting the data